server.port: ${SERVER_PORT:5000}

spring:
  data:
    mongodb:
      host: ${MONGO_HOST:localhost}
      port: ${MONGO_PORT:27017}
      database: ${MONGO_DATABASE:api}
      username: ${MONGO_USERNAME:admin}
      password: ${MONGO_PASSWORD:admin}